name: Build Android APK (Flutter)

on:
  workflow_dispatch:          # تشغيل يدوي من تبويب Actions
  push:
    tags:
      - 'v*'                  # يبني تلقائياً عند إنشاء Tag مثل v0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
      - name: Create GitHub Release and upload APKs
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
