name: Build Android APK (Flutter)

on:
  workflow_dispatch:        # تشغيل يدوي من تبويب Actions
  push:
    tags:
      - 'v*'                # يبني تلقائيًا عند إنشاء Tag مثل v0.1 أو v0.2

permissions:
  contents: write           # مطلوب علشان نرفع على GitHub Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      # بناء نسخة Release APK
      - name: Build RELEASE APK
        run: flutter build apk --release

      # رفع ملف APK كـ Artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      # عند البناء باستخدام Tag يرفع الـAPK إلى GitHub Release
      - name: Create GitHub Release and upload APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
