name: Build Android APK (Flutter)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Show Flutter version
        run: flutter --version

      # ✅ أنشئ هيكل المشروع كاملاً (android/، gradle، إلخ) إن لم يكن موجوداً
      - name: Ensure Flutter android project exists
        run: |
          flutter create . \
            --platforms=android \
            --project-name noor_arabe_light \
            --org com.noorarabe \
            --overwrite

      - name: Pub get
        run: flutter pub get

      # يمكنك الاكتفاء بالـ Debug للتجربة
      - name: Build DEBUG APK
        run: flutter build apk --debug

      # (اختياري) بناء Release
      - name: Build RELEASE APK
        run: flutter build apk --release

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release and upload APKs
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
